### ISSUE TITLE
Post load cached venv

### ISSUE THREAD

**Issue by scarrazza** [qibogang/workflows#64]
It seems that the post load cache venv is forcing all tests in qibo to fail, e.g.:

https://github.com/qiboteam/qibo/actions/runs/8571390230/job/23491514141

We can wait some days and check if github has fixed this issue, otherwise we should consider dropping it.

**Comment by alecandido** [comment]
This should be solved in https://github.com/qiboteam/workflows/tree/v1 (and also in https://github.com/qiboteam/workflows/tree/v2, but that's not recommended for general use yet).
